### ISSUE TITLE
Visual Bug

### ISSUE THREAD

**Issue by Pichu123** [simonk21/HW4d#2]
Current Card is Shaded

Steps to Recreate:
1. Run the game
2. When you have a card that can trump the current card( for example: you have a 7 of clubs when the current card to beat is a 5 of hearts), then play that card.

When you play the card, it will become the new current card, however, the card will be shaded. The card should only be shaded when a player selects a card.-Justin Cao

**Comment by malikh22** [comment]
This may not actually be a problem. The card is shaded as it is the card you played as opposed to a card played by the computer. However, I see how this can be confusing. Maybe we could make them look different from each other.

**Comment by Pichu123** [comment]
The bug was fixed, the played card that trumped the current card has the correct shading.Nice work!

**Comment by simonk21** [comment]
The card is no longer shaded in the current set.
